### ISSUE TITLE
Doesn't work if uploads aren't in wp-content/uploads

### ISSUE THREAD

**Issue by rosswintle** [billerickson/BE-Media-from-Production#1]
First of all, thanks for the awesome plugin. So helpful.

I've installed this on a new client's site where I'm taking over support of an existing site where the old developer has gone away.

The old developer has a bit of an odd `wp-config.php` and one of the things it does is:

```
define('WP_CONTENT_URL', "http://{$_SERVER['SERVER_NAME']}");
```

and his directory structure reflects this.

BE-Media-from-Production doesn't work in this setup.

At the very least, line 196 reads:

```
if( strpos( $url, 'wp-content/uploads' ) ) {
```

and should probably be changed so that it matches the WP_CONTENT_URL

```
if( false !== strpos( $url, WP_CONTENT_URL . '/uploads' ) ) {
```

(Note that we could now get a 0 from `strpos` and so we need the type-specific comparison)

You may also want to test for, and use if necessary, the UPLOADS constant (though, unlike WP_CONTENT_URL, this doesn't seem to be set by default, and will need to be tested for)

**Comment by billerickson** [comment]
That's a great point. Do you think you could put together a patch?

**Comment by rosswintle** [comment]
Hi Bill, sorry for the delay, I've been on holiday this last week. I have a working patch that uses `WP_CONTENT_URL` but not UPLOADS. I'll have to set up a proper test for both. But yes, I'll attempt to make a pull request in the near future.

Thanks
