### ISSUE TITLE
Deploy 1.5 to the WP repository as well

### ISSUE THREAD

**Issue by Levdbas** [billerickson/BE-Media-from-Production#10]
Hi Bill,

I just saw that you've released version 1.5 that includes constants. Could you release this version on the WordPress repository as well? To automate the process of publishing a new version on github and publishing it on the WP repo could be automated with a tool like: https://github.com/10up/action-wordpress-plugin-deploy

**Comment by billerickson** [comment]
Sorry for the delay. I just updated the version on WordPress.org

Thanks
