### ISSUE TITLE
ACF Flexible Content Pagebuilder - image links broken

### ISSUE THREAD

**Issue by billiemead** [billerickson/BE-Media-from-Production#18]
Hi,

Awesome plugin... ty. 

I wanted to try to troubleshoot and see why image links are broken when using ACF Flexible Content as a page builder. I am not sure if you're aware of that workflow and if so, had any hints where to look?

[https://wptips.dev/diy-page-builder-with-acf/](url)

Cheers~

**Comment by billerickson** [comment]
How are the images being output on the page? 

The plugin only updates urls [using these filters](https://github.com/billerickson/BE-Media-from-Production/blob/master/be-media-from-production.php#L56-L61), so it will fix images displayed using `the_post_thumbnail()`, `get_the_post_thumbnail()`, `wp_get_attachment_image()`. 

It will also update any `<img>` elements in the main post content that passes through `the_content` filter.

If you have custom markup outputting content, you could apply `the_content` filter to it to ensure the images are updated. Ex:

```
$content = get_field( 'content' );
echo apply_filters( 'the_content', $content );
```

**Comment by billiemead** [comment]
Brilliant! Thank you and I'll update here with the changes for ACF Flexible content.
