### ISSUE TITLE
Images in the core/image block in editor are not updated

### ISSUE THREAD

**Issue by billerickson** [billerickson/BE-Media-from-Production#20]
@graylaurenm or anyone else, have you found a filter that we could use to target images in the editor? At some point in a recent WordPress update, BE Media from Production stopped updating the URLs of these images. They still work correctly on the frontend.

![screenshot](https://p198.p4.n0.cdn.getcloudapp.com/items/X6u7RWYg/071e074a-9dd4-42bd-9474-30feb79f5e5d.jpg?source=viewer&v=508901fe59c8b1a68db0026ff3aa34ec)

**Comment by graylaurenm** [comment]
Completed?! I was working on this! 😂  Glad to see you found a solution. 🙂

**Comment by billerickson** [comment]
Erik Torsner at WPEngine / WP Migrate pointed me in the right direction on Twitter. They used `the_post` filter to do the same thing in WP Offload Media.
