### ISSUE TITLE
Add Changelog to Readme.txt for WP.org Repo

### ISSUE THREAD

**Issue by mrwweb** [billerickson/BE-Media-from-Production#21]
The v1.7.0 update didn't seem to have any changelog in the repo. I recall there previously was one, though I didn't go digging for it. It would be great to get that updated, especially to clarify the new branding/plugin co-owner.

Thanks for the great plugin!

**Comment by billerickson** [comment]
That's a great point! I just added [a changelog](https://github.com/billerickson/BE-Media-from-Production/blob/master/CHANGELOG.md) and described the recent update. At some point I'll go through the history and fill in the previous updates, but don't have time for that right now.

We recently updated my agency's website ([CultivateWP](https://cultivatewp.com)), and alongside it we updated the branding and documentation on all [our plugins](https://cultivatewp.com/our-plugins/). Any plugins I built for use by my clients or our development process now have CultivateWP as an author.
