### ISSUE TITLE
Consider adding documentation for getting media from sites behind HTTP Auth

### ISSUE THREAD

**Issue by mrwweb** [billerickson/BE-Media-from-Production#22]
I'm currently using this plugin on a site where I need to use media from a staging site that is behind HTTP Auth (i.e., the little popup browser window that asks for a username and password).

I was pleased to figure out that you can make this work with this plugin as-is list this:

> https://user:password@example.org

That gets you the media from example.org where the auth username is "user" and the password is "password".

It seems like this might be worth quickly documenting (maybe in a FAQ in the readme)? Happy to submit a PR if you'd like :)

**Comment by billerickson** [comment]
Hi Mark,

I thought about adding that to the documentation but it seems to be browser specific. As of a year or two ago, Chrome doesn't let me load images that include the basic auth login in the URL. Does it work for you in Chrome and other browsers?

**Comment by mrwweb** [comment]
Very interesting! It still works in Firefox, but I see now that it doesn't work in Chrome/Edge (and I don't have Safari handy to test right now). It seems like supporting that in other browsers would require quite a bit of new overhead in the plugin, so I'd understand not adding it.

Who knows if FF will continue to support this much longer, so I suppose it's probably not work documenting.
