### ISSUE TITLE
Doesn't work for subsites on a multsite install

### ISSUE THREAD

**Issue by electricbrick** [billerickson/BE-Media-from-Production#3]
Could you add a filter that accomodates for multisite installs, a la:

https://stackoverflow.com/questions/35781410/wordpress-multisite-wp-upload-dir-wrong

**Comment by billerickson** [comment]
I'm happy to accept a pull request, or more guidance on where a filter would be useful. I never use multisite so wouldn't be comfortable writing it on my own.

**Comment by jgomke** [comment]
Hey Bill,
I managed to get this issue resolved for the most part on my local multisite install but I had to tweak the following function in the core BE-Media-from-Production file to be an if/else statement that checks if the site is multisite. 
`/**
	 * Convert a URL to a local filename
	 *
	 * @since 1.4.0
	 * @param string $url
	 * @return string $local_filename
	 */
	function local_filename( $url ) {
		$upload_locations = wp_upload_dir();
		if( is_multisite() ) {
			$local_filename = str_replace( $upload_locations[ 'baseurl' ], $upload_locations[ 'subdir' ], $url );
			return $local_filename;
			}
		else{
			$local_filename = str_replace( $upload_locations[ 'baseurl' ], $upload_locations[ 'basedir' ], $url );
			return $local_filename;
		}

	}
`

**Comment by jgomke** [comment]
I also used the following snippet in my theme helpers that uses if/else statement as well to detect sub-sites.  
```
/**
 *  For Bill Erickson Plugin Media Production URL 
 *
 *
 */
add_filter( 'be_media_from_production_url', 'prefix_production_url' );
function prefix_production_url( $url ) {
	$blog_details = get_blog_details();

	if( is_multisite() && !is_main_site() ){
		return 'https://www.mywebsite.com'.$blog_details->path;
	}
	else{
		return 'https://www.mywebsite.com';
	
	} 
}
```

**Comment by jgomke** [comment]
My apologies if the code is sub-par. But thought I'd share and see if this helps anyone.
