### ISSUE TITLE
Non-image urls

### ISSUE THREAD

**Issue by jonschr** [billerickson/BE-Media-from-Production#4]
Love this functionality. I'm installing it on a number of sites, and this is going to let me not have to maintain so much space on my tiny little mac for larger sites.

I wonder if it would be possible to add functionality for the wp_get_attachment_url function in addition to the ones already supported (wp_get_attachment_image_src, wp_get_attachment_image_attributes, wp_prepare_attachment_for_js, the_content); this obviously could be used for images, but my use case is actually video files that we're pulling in via ACF to add background video.

This is how it's being pulled in currently:

https://gist.github.com/jonschr/224d56a40c9f7e5931355a65018e1b44

**Comment by billerickson** [comment]
Yes, we should definitely add this. Can you test and submit a patch?

It should be as simple as adding `add_filter( 'wp_get_attachment_url', array( $this, 'update_image_url' ) );` [right here](https://github.com/billerickson/BE-Media-from-Production/blob/736214d572f359a7a4ba1a52baf280de43b691e7/be-media-from-production.php#L89)

**Comment by jonschr** [comment]
Yeah, will do.

**Comment by billerickson** [comment]
Merged in #5
