### ISSUE TITLE
Local image exists check fails for local images' srcset attribute

### ISSUE THREAD

**Issue by robincornett** [billerickson/BE-Media-from-Production#7]
If an image exists locally and is output with a srcset attribute, it fails the [local_image_exists check](https://github.com/billerickson/BE-Media-from-Production/blob/master/be-media-from-production.php#L244), so the plugin replaces the URLs in the srcset with the production URL.

It looks like this is because the `[image_attr](https://github.com/billerickson/BE-Media-from-Production/blob/master/be-media-from-production.php#L156)` method passes the srcset value to the image updater, but the local image check is expecting a URL, and the srcset will be a string such as:

```
http://local.example.test/wp-content/uploads/2019/05/tim-foster-264461.jpg 4599w, http://local.example.test/wp-content/uploads/2019/05/tim-foster-264461-300x206.jpg 300w, http://local.example.test/wp-content/uploads/2019/05/tim-foster-264461-768x526.jpg 768w, http://local.example.test/wp-content/uploads/2019/05/tim-foster-264461-1024x702.jpg 1024w
```
which will not return true for the file existing.

Actually, I think all that needs to happen is to change line 159 to this:

```
$attr['srcset'] = $this->update_image_url( $attr['src'] );
```

(passing just `src` to the updater instead of `srcset`... this fixed the issue for me locally.

**Comment by robincornett** [comment]
Related: local images used in the WordPress core cover block (as a background) end up failing the local_image_exists check as well because the [regex done on images](https://github.com/billerickson/BE-Media-from-Production/blob/master/be-media-from-production.php#L197) in the content doesn't remove the trailing `)` from the image path.

One way to fix it would be to just strip any `)` from image URLs in the content, inserting this right before line 201:

```
$url     = str_replace( ')', '', $url );
```

but there may be a better way to resolve that in the regex itself; my regex wobbles. But adding this line above the `$new_url` assignment does work for me.

**Comment by billerickson** [comment]
The source set issue was fixed in the latest release. We are now exploding the srcset and applying `$this->update_image_url()` to each individual URL: https://github.com/billerickson/BE-Media-from-Production/blob/master/be-media-from-production.php#L90-L92

I'm closing this ticket as the original issue was addressed. If you are still having an issue with the core cover block, can you open a separate issue?

Thanks
